{"id": "GHSA-jm77-qphf-c4w8", "package": "pypi:cryptography", "purl": "pkg:pypi/cryptography@36.0.2", "package_type": "pypi", "package_usage": "N/A", "version": "36.0.2", "fix_version": "41.0.3", "severity": "LOW", "cvss_score": "2.0", "short_description": "# pyca/cryptography's wheels include vulnerable OpenSSL\npyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 0.8-41.0.2 are vulnerable to several security issues. More details about the vulnerabilities themselves can be found in https://www.openssl.org/news/secadv/20230731.txt, https://www.openssl.org/news/secadv/20230719.txt, and https://www.openssl.org/news/secadv/20230714.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.", "related_urls": ["https://github.com/pyca/cryptography/security/advisories/GHSA-jm77-qphf-c4w8", "https://github.com/pyca/cryptography/commit/b22271cf3c3dd8dc8978f8f4b00b5c7060b6538d", "https://github.com/pyca/cryptography/commit/bfa4d95f0f356f2d535efd5c775e0fb3efe90ef2", "https://github.com/pyca/cryptography", "https://www.openssl.org/news/secadv/20230714.txt", "https://www.openssl.org/news/secadv/20230719.txt", "https://www.openssl.org/news/secadv/20230731.txt"], "occurrence_count": 0, "reachable_flows": 0}
{"id": "CVE-2023-23931", "package": "pypi:cryptography", "purl": "pkg:pypi/cryptography@36.0.2", "package_type": "pypi", "package_usage": "N/A", "version": "36.0.2", "fix_version": "39.0.1", "severity": "MEDIUM", "cvss_score": "6.5", "short_description": "# Cipher.update_into can corrupt memory if passed an immutable python object as the outbuf\\nPreviously, `Cipher.update_into` would accept Python objects which implement the buffer protocol, but provide only immutable buffers:\\n\\n```pycon\\n>>> outbuf = b\"\\x00\" * 32\\n>>> c = ciphers.Cipher(AES(b\"\\x00\" * 32), modes.ECB()).encryptor()\\n>>> c.update_into(b\"\\x00\" * 16, outbuf)\\n16\\n>>> outbuf\\nb'\\xdc\\x95\\xc0x\\xa2@\\x89\\x89\\xadH\\xa2\\x14\\x92\\x84 \\x87\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00'\\n```\\n\\nThis would allow immutable objects (such as `bytes`) to be mutated, thus violating fundamental rules of Python. This is a soundness bug -- it allows programmers to misuse an API, it cannot be exploited by attacker controlled data alone.\\n\\nThis now correctly raises an exception.\\n\\nThis issue has been present since `update_into` was originally introduced in cryptography 1.8.", "related_urls": ["https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r", "https://nvd.nist.gov/vuln/detail/CVE-2023-23931", "https://github.com/pyca/cryptography/pull/8230/commits/94a50a9731f35405f0357fa5f3b177d46a726ab3", "https://github.com/pyca/cryptography/commit/d6951dca25de45abd52da51b608055371fbcde4e", "https://github.com/pyca/cryptography"], "occurrence_count": 0, "reachable_flows": 0}
{"id": "CVE-2022-42969", "package": "pypi:py", "purl": "pkg:pypi/py@1.11.0", "package_type": "pypi", "package_usage": "N/A", "version": "1.11.0", "fix_version": null, "severity": "HIGH", "cvss_score": "7.5", "short_description": "# ReDoS in py library when used with subversion \nThe py library through 1.11.0 for Python allows remote attackers to conduct a ReDoS (Regular expression Denial of Service) attack via a Subversion repository with crafted info data, because the InfoSvnCommand argument is mishandled.\n\nThe particular codepath in question is the regular expression at `py._path.svnurl.InfoSvnCommand.lspattern` and is only relevant when dealing with subversion (svn) projects. Notably the codepath is not used in the popular pytest project. The developers of the pytest package have released version `7.2.0` which removes their dependency on `py`. Users of `pytest` seeing alerts relating to this advisory may update to version `7.2.0` of `pytest` to resolve this issue. See https://github.com/pytest-dev/py/issues/287#issuecomment-1290407715 for additional context.\n\n## Related CVE(s)\nCVE-2022-42969, PYSEC-2022-42969", "related_urls": ["https://nvd.nist.gov/vuln/detail/CVE-2022-42969", "https://github.com/pytest-dev/py/issues/287", "https://github.com/pytest-dev/py/issues/288", "https://github.com/pytest-dev/pytest/issues/10392", "https://github.com/pytest-dev/py", "https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316", "https://news.ycombinator.com/item?id=34163710", "https://pypi.org/project/py"], "occurrence_count": 0, "reachable_flows": 0}
{"id": "CVE-2023-0286", "package": "pypi:cryptography", "purl": "pkg:pypi/cryptography@36.0.2", "package_type": "pypi", "package_usage": "N/A", "version": "36.0.2", "fix_version": "39.0.1", "severity": "HIGH", "cvss_score": "7.4", "short_description": "# Vulnerable OpenSSL included in cryptography wheels\npyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 0.8.1-39.0.0\tare vulnerable to a security issue. More details about the vulnerabilities themselves can be found in https://www.openssl.org/news/secadv/20221213.txt and https://www.openssl.org/news/secadv/20230207.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.\n\n\n\n## Related CVE(s)\nCVE-2023-0286, RUSTSEC-2023-0006", "related_urls": ["https://github.com/pyca/cryptography/security/advisories/GHSA-x4qr-2fvf-3mr5", "https://nvd.nist.gov/vuln/detail/CVE-2023-0286", "https://access.redhat.com/security/cve/cve-2023-0286", "https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.6.2-relnotes.txt", "https://ftp.openbsd.org/pub/OpenBSD/patches/7.2/common/018_x509.patch.sig", "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2c6c9d439b484e1ba9830d8454a34fa4f80fdfe9", "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2f7530077e0ef79d98718138716bc51ca0cad658", "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=fd2af07dc083a350c959147097003a14a5e8ac4d", "https://github.com/pyca/cryptography", "https://rustsec.org/advisories/RUSTSEC-2023-0006.html", "https://security.gentoo.org/glsa/202402-08", "https://www.openssl.org/news/secadv/20230207.txt"], "occurrence_count": 0, "reachable_flows": 0}
{"id": "CVE-2023-41419", "package": "pypi:gevent", "purl": "pkg:pypi/gevent@21.12.0", "package_type": "pypi", "package_usage": "N/A", "version": "21.12.0", "fix_version": "23.9.0", "severity": "CRITICAL", "cvss_score": "9.8", "short_description": "# Gevent allows remote attacker to escalate privileges\nAn issue in Gevent before version 23.9.0 allows a remote attacker to escalate privileges via a crafted script to the WSGIServer component.\n\n## Related CVE(s)\nCVE-2023-41419, PYSEC-2023-177", "related_urls": ["https://nvd.nist.gov/vuln/detail/CVE-2023-41419", "https://github.com/gevent/gevent/issues/1989", "https://github.com/gevent/gevent/commit/2f53c851eaf926767fbac62385615efd4886221c", "https://github.com/gevent/gevent", "https://github.com/pypa/advisory-database/tree/main/vulns/gevent/PYSEC-2023-177.yaml", "http://www.gevent.org/changelog.html"], "occurrence_count": 0, "reachable_flows": 0}
{"id": "CVE-2024-0727", "package": "pypi:cryptography", "purl": "pkg:pypi/cryptography@36.0.2", "package_type": "pypi", "package_usage": "N/A", "version": "36.0.2", "fix_version": "42.0.2", "severity": "MEDIUM", "cvss_score": "5.5", "short_description": "# Null pointer dereference in PKCS12 parsing\nIssue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.", "related_urls": ["https://nvd.nist.gov/vuln/detail/CVE-2024-0727", "https://github.com/github/advisory-database/pull/3472", "https://github.com/openssl/openssl/pull/23362", "https://github.com/alexcrichton/openssl-src-rs/commit/add20f73b6b42be7451af2e1044d4e0e778992b2", "https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2", "https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a", "https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c", "https://github.com/pyca/cryptography/commit/3519591d255d4506fbcd0d04037d45271903c64d", "https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8", "https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539", "https://security.netapp.com/advisory/ntap-20240208-0006", "https://www.openssl.org/news/secadv/20240125.txt", "http://www.openwall.com/lists/oss-security/2024/03/11/1"], "occurrence_count": 0, "reachable_flows": 0}
{"id": "CVE-2023-50782", "package": "pypi:cryptography", "purl": "pkg:pypi/cryptography@36.0.2", "package_type": "pypi", "package_usage": "N/A", "version": "36.0.2", "fix_version": "42.0.2", "severity": "HIGH", "cvss_score": "7.5", "short_description": "# Python Cryptography package vulnerable to Bleichenbacher timing oracle attack\nA flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.", "related_urls": ["https://nvd.nist.gov/vuln/detail/CVE-2023-50782", "https://github.com/pyca/cryptography/issues/9785", "https://access.redhat.com/security/cve/CVE-2023-50782", "https://bugzilla.redhat.com/show_bug.cgi?id=2254432", "https://github.com/pyca/cryptography"], "occurrence_count": 0, "reachable_flows": 0}
{"id": "GHSA-v8gr-m533-ghj9", "package": "pypi:cryptography", "purl": "pkg:pypi/cryptography@36.0.2", "package_type": "pypi", "package_usage": "N/A", "version": "36.0.2", "fix_version": "41.0.4", "severity": "LOW", "cvss_score": "2.0", "short_description": "# Vulnerable OpenSSL included in cryptography wheels\npyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 2.5-41.0.3 are vulnerable to several security issues. More details about the vulnerabilities themselves can be found in https://www.openssl.org/news/secadv/20230908.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.", "related_urls": ["https://github.com/pyca/cryptography/security/advisories/GHSA-v8gr-m533-ghj9", "https://github.com/pyca/cryptography/commit/fc11bce6930e591ce26a2317b31b9ce2b3e25512", "https://github.com/pyca/cryptography"], "occurrence_count": 0, "reachable_flows": 0}
{"id": "GHSA-5cpq-8wj7-hf2v", "package": "pypi:cryptography", "purl": "pkg:pypi/cryptography@36.0.2", "package_type": "pypi", "package_usage": "N/A", "version": "36.0.2", "fix_version": "41.0.0", "severity": "LOW", "cvss_score": "2.0", "short_description": "# Vulnerable OpenSSL included in cryptography wheels\npyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 0.5-40.0.2 are vulnerable to a security issue. More details about the vulnerability itself can be found in https://www.openssl.org/news/secadv/20230530.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.", "related_urls": ["https://github.com/pyca/cryptography/security/advisories/GHSA-5cpq-8wj7-hf2v", "https://github.com/pyca/cryptography/commit/8708245ccdeaff21d65eea68a4f8d2a7c5949a22", "https://cryptography.io/en/latest/changelog/#v41-0-0", "https://github.com/pyca/cryptography"], "occurrence_count": 0, "reachable_flows": 0}
{"id": "CVE-2023-49083", "package": "pypi:cryptography", "purl": "pkg:pypi/cryptography@36.0.2", "package_type": "pypi", "package_usage": "N/A", "version": "36.0.2", "fix_version": "41.0.6", "severity": "MEDIUM", "cvss_score": "5.9", "short_description": "# cryptography vulnerable to NULL-dereference when loading PKCS7 certificates\\n### Summary\\n\\nCalling `load_pem_pkcs7_certificates` or `load_der_pkcs7_certificates` could lead to a NULL-pointer dereference and segfault.\\n\\n### PoC\\nHere is a Python code that triggers the issue:\\n```python\\nfrom cryptography.hazmat.primitives.serialization.pkcs7 import load_der_pkcs7_certificates, load_pem_pkcs7_certificates\\n\\npem_p7 = b\"\"\"\\n-----BEGIN PKCS7-----\\nMAsGCSqGSIb3DQEHAg==\\n-----END PKCS7-----\\n\"\"\"\\n\\nder_p7 = b\"\\x30\\x0B\\x06\\x09\\x2A\\x86\\x48\\x86\\xF7\\x0D\\x01\\x07\\x02\"\\n\\nload_pem_pkcs7_certificates(pem_p7)\\nload_der_pkcs7_certificates(der_p7)\\n```\\n\\n### Impact\\nExploitation of this vulnerability poses a serious risk of Denial of Service (DoS) for any application attempting to deserialize a PKCS7 blob/certificate. The consequences extend to potential disruptions in system availability and stability.\\n\\n## Related CVE(s)\\nCVE-2023-49083, PYSEC-2023-254", "related_urls": ["https://github.com/pyca/cryptography/security/advisories/GHSA-jfhm-5ghh-2f97", "https://nvd.nist.gov/vuln/detail/CVE-2023-49083", "https://github.com/pyca/cryptography/pull/9926", "https://github.com/pyca/cryptography/commit/f09c261ca10a31fe41b1262306db7f8f1da0e48a", "https://github.com/pyca/cryptography", "https://github.com/pypa/advisory-database/tree/main/vulns/cryptography/PYSEC-2023-254.yaml", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QMNTYMUGFJSDBYBU22FUYBHFRZODRKXV", "http://www.openwall.com/lists/oss-security/2023/11/29/2"], "occurrence_count": 0, "reachable_flows": 0}
